/**
 * migrate-store.cjs
 *
 * Reads CSV files from docs/ and generates seed-store.sql
 * with INSERT statements for the stancil-store D1 database.
 *
 * Usage:  node scripts/migrate-store.cjs
 * Output: scripts/seed-store.sql
 */

const fs = require("fs");
const path = require("path");

const DOCS_DIR = path.join(__dirname, "..", "docs");
const OUTPUT_FILE = path.join(__dirname, "seed-store.sql");

// CSV file → table mapping (filenames are misleading!)
const CSV_TABLE_MAP = [
  { file: "Products.csv", table: "colors" },
  { file: "Orders 1.csv", table: "products" },
  { file: "variants.csv", table: "product_variants" },
  { file: "orderid.csv", table: "orders" },
  { file: "Orders.csv", table: "order_items" },
  { file: "Employees.csv", table: "profiles" },
  { file: "settings.csv", table: "store_settings" },
  { file: "swag bags.csv", table: "swag_bags" },
  { file: "swagbags.csv", table: "swag_bag_items" },
];

// Boolean columns that need true/false → 1/0 conversion
const BOOLEAN_COLUMNS = new Set([
  "active",
  "is_swag_bag",
  "is_custom",
  "is_credit_allowed",
  "will_reorder",
  "order_fulfilled",
  "item_fulfilled",
  "is_open",
  "can_resubmit",
]);

/**
 * Parse a CSV line handling quoted fields (with commas and quotes inside).
 */
function parseCsvLine(line) {
  const fields = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];

    if (inQuotes) {
      if (ch === '"') {
        // Check for escaped quote ("")
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i++; // skip next quote
        } else {
          inQuotes = false;
        }
      } else {
        current += ch;
      }
    } else {
      if (ch === '"') {
        inQuotes = true;
      } else if (ch === ",") {
        fields.push(current);
        current = "";
      } else {
        current += ch;
      }
    }
  }
  fields.push(current);
  return fields;
}

/**
 * Escape a string value for SQL (single quotes).
 */
function sqlEscape(val) {
  return val.replace(/'/g, "''");
}

/**
 * Convert a raw CSV value to a SQL literal.
 */
function toSqlValue(val, columnName) {
  const trimmed = val.trim();

  // Handle NULL
  if (trimmed === "" || trimmed.toLowerCase() === "null") {
    return "NULL";
  }

  // Handle booleans
  if (BOOLEAN_COLUMNS.has(columnName)) {
    const lower = trimmed.toLowerCase();
    if (lower === "true" || lower === "1") return "1";
    if (lower === "false" || lower === "0") return "0";
    // If it doesn't match, treat as NULL
    return "NULL";
  }

  // Check if it's a number (but not something that looks like a UUID or timestamp)
  if (
    /^-?\d+(\.\d+)?$/.test(trimmed) &&
    !trimmed.includes("-") === false
  ) {
    // Actually, let's be more precise: only treat as number if it's purely numeric
  }

  // For numeric-looking values that aren't IDs or timestamps
  if (/^-?\d+(\.\d+)?$/.test(trimmed) && trimmed.length < 16) {
    return trimmed;
  }

  // Everything else is a text value
  return `'${sqlEscape(trimmed)}'`;
}

/**
 * Process a single CSV file and return INSERT statements.
 */
function processCsv(filePath, tableName) {
  const content = fs.readFileSync(filePath, "utf-8");
  const lines = content.split(/\r?\n/).filter((l) => l.trim() !== "");

  if (lines.length < 2) {
    console.log(`  Skipping ${tableName}: no data rows`);
    return "";
  }

  const headers = parseCsvLine(lines[0]);
  const statements = [];

  for (let i = 1; i < lines.length; i++) {
    const values = parseCsvLine(lines[i]);

    // Skip rows that don't match header count (malformed)
    if (values.length !== headers.length) {
      console.warn(
        `  Warning: ${tableName} row ${i} has ${values.length} fields, expected ${headers.length}. Skipping.`
      );
      continue;
    }

    const sqlValues = values.map((v, idx) => toSqlValue(v, headers[idx]));
    const columnList = headers.map((h) => `"${h}"`).join(", ");
    const valueList = sqlValues.join(", ");

    statements.push(
      `INSERT INTO ${tableName} (${columnList}) VALUES (${valueList});`
    );
  }

  return statements.join("\n");
}

// ── Main ──────────────────────────────────────────────────────
function main() {
  const parts = [
    "-- seed-store.sql",
    "-- Auto-generated by scripts/migrate-store.cjs",
    `-- Generated: ${new Date().toISOString()}`,
    "",
    "PRAGMA foreign_keys = OFF;",
    "-- Disable FK checks during bulk insert, re-enable at end.",
    "",
  ];

  // Process in order that respects FK dependencies:
  // colors, products, product_variants first (no FKs or FK to products)
  // then orders, order_items, profiles, store_settings, swag_bags, swag_bag_items
  const insertOrder = [
    { file: "Products.csv", table: "colors" },
    { file: "Orders 1.csv", table: "products" },
    { file: "variants.csv", table: "product_variants" },
    { file: "orderid.csv", table: "orders" },
    { file: "Orders.csv", table: "order_items" },
    { file: "Employees.csv", table: "profiles" },
    { file: "settings.csv", table: "store_settings" },
    { file: "swag bags.csv", table: "swag_bags" },
    { file: "swagbags.csv", table: "swag_bag_items" },
  ];

  for (const { file, table } of insertOrder) {
    const filePath = path.join(DOCS_DIR, file);

    if (!fs.existsSync(filePath)) {
      console.warn(`  WARNING: ${file} not found, skipping ${table}`);
      continue;
    }

    console.log(`Processing ${file} → ${table}`);
    const sql = processCsv(filePath, table);

    if (sql) {
      parts.push(`-- ── ${table} ──`);
      parts.push(sql);
      parts.push("");
    }
  }

  parts.push("PRAGMA foreign_keys = ON;");
  parts.push("");

  fs.writeFileSync(OUTPUT_FILE, parts.join("\n"), "utf-8");
  console.log(`\nDone! Output written to: ${OUTPUT_FILE}`);
}

main();
